### ISSUE TITLE
QL-005 Highscores

### ISSUE THREAD

**Issue by sebue98** [sw21-tug/Team_19#5]
As a registered User, I want to see my highscores saved, so that I can compare with my friends

**Comment by grudoa** [comment]
fyi an api call has to be added here. I would recommend localhost:8000/highscore and Http-type POST and as body parameter the mail address of the user

also something like overrideHighscore(email) for example has to be added to database interface and requestHandler and a highscore property should be added to the user class

**Comment by grudoa** [comment]
@emiliabodirnea and I did implement the game logic and also started there with the highscores in the backend. We defined the methods; implemented them in RequestHandler, but did not implement them right for DBManager. For this task you have to implement this methods and implement the displaying of the highscore itself
